services: 
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    privileged: true
    user: root
    volumes:
      - /app
    ports:
      - "8080:8080"
      - "50000:50000"

networks:
  mynetwork: 